<?php

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

/**
 * @return void
 */
function sater_mediaflow_video_register_field_group(): void
{
    acf_add_local_field_group([
        'key' => 'group_sater_mediaflow_video_mod',
        'title' => __('Mediaflow video', 'sater-mediaflow-video'),
        'fields' => sater_mediaflow_video_get_mediaflow_fields(),
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-video',
                ],
            ],
            [
                [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/video',
                ],
            ],
        ],
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
    ]);
}

/**
 * @return list<array<string, mixed>>
 */
function sater_mediaflow_video_get_mediaflow_fields(): array
{
    $showWhenMediaflow = [
        [
            [
                'field' => SATER_VIDEO_TYPE_FIELD_KEY,
                'operator' => '==',
                'value' => SATER_VIDEO_TYPE_MEDIAFLOW,
            ],
        ],
    ];

    return [
        [
            'key' => 'field_sater_mediaflow_video_message',
            'label' => __('Mediaflow video', 'sater-mediaflow-video'),
            'name' => 'mediaflow_picker',
            'type' => 'message',
            'instructions' => __('Choose a video that is approved for web publishing in Mediaflow.', 'sater-mediaflow-video'),
            'required' => 0,
            'conditional_logic' => $showWhenMediaflow,
            'wrapper' => [
                'width' => '',
                'class' => 'sater-mediaflow-video-message',
                'id' => '',
            ],
            'message' => '<div class="sater-mediaflow-video-admin" data-sater-mediaflow-video-admin></div>',
            'new_lines' => 'br',
            'esc_html' => 0,
        ],
        [
            'key' => SATER_MEDIAFLOW_ID_FIELD_KEY,
            'label' => __('Mediaflow file ID', 'sater-mediaflow-video'),
            'name' => 'mediaflow_id',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => $showWhenMediaflow,
            'wrapper' => [
                'width' => '',
                'class' => 'sater-mediaflow-video-id-field',
                'id' => '',
            ],
            'default_value' => '',
            'min' => 1,
            'max' => '',
            'step' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => SATER_MEDIAFLOW_EMBED_FIELD_KEY,
            'label' => __('Embed code', 'sater-mediaflow-video'),
            'name' => 'mediaflow_embed',
            'type' => 'textarea',
            'instructions' => __('Generated by Mediaflow when you select a video.', 'sater-mediaflow-video'),
            'required' => 1,
            'conditional_logic' => $showWhenMediaflow,
            'wrapper' => [
                'width' => '',
                'class' => 'sater-mediaflow-video-embed-field',
                'id' => '',
            ],
            'default_value' => '',
            'maxlength' => '',
            'rows' => 4,
            'placeholder' => '',
            'new_lines' => '',
        ],
    ];
}
